baseURL = 'https://chymera.eu/'
languageCode = 'en-us'
title = 'Chymera.eu'

[markup]
	[markup.goldmark.renderer]
		unsafe = true

[params]
	BookTheme = 'light'
	OnlyBookLogo = "/logo.png"
	BookDateFormat = '2006-01-02'

[taxonomies]
	tag = 'tags'

[menu]
	[[menu.after]]
		identifier = 'blog'
		name = 'Blog'
		pre = "<b>"
		url = '/posts/'
		post = "</b>"
		weight = -110

